name: Openterface APK Packaging

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Clean Gradle
      run: ./gradlew clean

    - name: Build with Gradle
      run: ./gradlew assemble --info

    # Store only APK files as artifacts
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-builds
        path: |
          app/build/outputs/apk/**/*.apk
        retention-days: 90