name: Android Lint Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Setup Lint Report Branch
      run: |
        git fetch origin lint_check_report || true
        git checkout -B lint_check_report

    # Generate lint baseline for app module
    - name: Generate App Lint Baseline
      run: |
        ./gradlew :app:lintDebug || true
        if [ -f "app/lint-baseline.xml" ]; then
          git add app/lint-baseline.xml
        fi

    # Generate lint baseline for libuvccamera module
    - name: Generate LibUVCCamera Lint Baseline
      run: |
        ./gradlew :libuvccamera:lintDebug || true
        if [ -f "libuvccamera/lint-baseline.xml" ]; then
          git add libuvccamera/lint-baseline.xml
        fi

    # Commit and push if there are changes
    - name: Commit and Push Changes
      run: |
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add/Update lint baseline files"
          git push -f origin lint_check_report
        fi

    # Run actual lint check after baseline is generated
    - name: Run Lint Check
      run: ./gradlew lint

    # Upload lint reports as artifacts
    - name: Upload Lint Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: lint-reports
        path: |
          app/build/reports/lint-results-debug.html
          libuvccamera/build/reports/lint-results-debug.html